import type { PizzaOrder } from "./types"

export const pizzaOrders: PizzaOrder[] = [
  {
    orderId: "PZA001",
    customerName: "John Doe",
    pizzaType: "Margherita",
    quantity: 2,
    orderDate: "2023-05-22T14:30:00",
    status: "Delivered",
  },
  {
    orderId: "PZA002",
    customerName: "Jane Smith",
    pizzaType: "Pepperoni",
    quantity: 1,
    orderDate: "2023-05-22T15:45:00",
    status: "Out for Delivery",
  },
  {
    orderId: "PZA003",
    customerName: "Robert Johnson",
    pizzaType: "Veggie Supreme",
    quantity: 3,
    orderDate: "2023-05-22T16:20:00",
    status: "Preparing",
  },
  {
    orderId: "PZA004",
    customerName: "Emily Davis",
    pizzaType: "Hawaiian",
    quantity: 2,
    orderDate: "2023-05-22T17:10:00",
    status: "Pending",
  },
  {
    orderId: "PZA005",
    customerName: "Michael Wilson",
    pizzaType: "BBQ Chicken",
    quantity: 1,
    orderDate: "2023-05-22T18:05:00",
    status: "Cancelled",
  },
  {
    orderId: "PZA006",
    customerName: "Sarah Brown",
    pizzaType: "Meat Lovers",
    quantity: 2,
    orderDate: "2023-05-22T18:30:00",
    status: "Pending",
  },
  {
    orderId: "PZA007",
    customerName: "David Miller",
    pizzaType: "Buffalo Chicken",
    quantity: 1,
    orderDate: "2023-05-22T19:15:00",
    status: "Preparing",
  },
  {
    orderId: "PZA008",
    customerName: "Jennifer Taylor",
    pizzaType: "Cheese",
    quantity: 3,
    orderDate: "2023-05-22T19:45:00",
    status: "Out for Delivery",
  },
  {
    orderId: "PZA009",
    customerName: "Thomas Anderson",
    pizzaType: "Supreme",
    quantity: 2,
    orderDate: "2023-05-22T20:20:00",
    status: "Delivered",
  },
  {
    orderId: "PZA010",
    customerName: "Lisa White",
    pizzaType: "Mushroom",
    quantity: 1,
    orderDate: "2023-05-22T21:00:00",
    status: "Pending",
  },
  {
    orderId: "PZA011",
    customerName: "James Martin",
    pizzaType: "Spinach & Feta",
    quantity: 2,
    orderDate: "2023-05-23T10:15:00",
    status: "Preparing",
  },
  {
    orderId: "PZA012",
    customerName: "Patricia Garcia",
    pizzaType: "Pepperoni & Mushroom",
    quantity: 1,
    orderDate: "2023-05-23T11:30:00",
    status: "Pending",
  },
]
